name: Terraform CI/CD

on:
  push:
    branches:
      - feature/main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_ami_id: ${{ secrets.TF_VAR_ami_id }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: |
          set +e
          terraform apply -auto-approve > terraform.log 2>&1
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

          if [ $EXIT_CODE -ne 0 ]; then
            echo "TERRAFORM_FAILED=true" >> $GITHUB_ENV
          fi

      - name: Debug Failure Flag
        run: |
          echo "Terraform failed flag: $TERRAFORM_FAILED"
      
      - name: Send Logs to Make.com
        if: env.TERRAFORM_FAILED == 'true'
        run: |
          LOG_CONTENT=$(head -n 50 terraform.log)

          JSON_PAYLOAD=$(jq -n --arg log "$LOG_CONTENT" '{log: $log}')

          curl -X POST https://hook.eu1.make.com/2rkt5kcllidnsy33kw13y5x6m6ywf7ie \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD"

      - name: Upload Terraform Logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-log
          path: terraform.log
