name: Terraform CI/CD

on:
  push:
    branches:
      - feature/main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_ami_id: ${{ secrets.TF_VAR_ami_id }}

    steps: 
      - name: Checkout 
        uses: actions/checkout@v3 
        
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3 

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/
        
      - name: Terraform Apply
        id: apply
        run: |
          set +e
          terraform apply -auto-approve 2>&1 | tee tf_output.log
          TF_EXIT=${PIPESTATUS[0]}
          echo "tf_exitcode=$TF_EXIT" >> $GITHUB_OUTPUT
          if [ $TF_EXIT -ne 0 ]; then
            echo "TF_FAILED=true" >> $GITHUB_ENV
          fi
          exit 0
        working-directory: terraform/

      - name: Debug Log File
        run: |
          echo "Terraform exit code: ${{ steps.apply.outputs.tf_exitcode }}"
          echo "TF_FAILED=${{ env.TF_FAILED }}"
          echo "---- LOG CONTENT ----"
          cat tf_output.log || echo "No log file found"
        working-directory: terraform/

      - name: Extract Errors with Python
        if: env.TF_FAILED == 'true'
        run: |
          python scripts/extract_tf_error.py \
            --stage apply \
            --log-file terraform/tf_output.log \
            --output terraform/payload.json \
            --repo "${{ github.repository }}" \
            --sha "${{ github.sha }}" \
            --branch "${{ github.ref_name }}" \
            --run-id "${{ github.run_id }}"
        
      - name: Send Logs to Make
        if: env.TF_FAILED == 'true'
        run: |
          echo "---- PAYLOAD PREVIEW ----"
          head -20 payload.json

          curl -X POST "${{ secrets.MAKE_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            --data-binary @payload.json
        working-directory: terraform/

      - name: Fail if apply failed
        if: env.TF_FAILED == 'true'
        run: exit 1
